name: sales_analytics
version: "1.0.0"
config-version: 2

profile: sales_analytics

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  sales_analytics:
    staging:
      +materialized: view
      +tags: ["staging"]
